name 'chef-nuc'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-nuc'
long_description 'Installs/Configures chef-nuc'
version '0.1.0'
